{
    "name": "Executive Dashboard",
    "version": "19.0.5.0.0",
    "category": "Productivity/Dashboards",
    "summary": "Interactive executive dashboard for Sales, CRM, Inventory, Purchase, Manufacturing, Maintenance, HR, Helpdesk, POS, Website, and Reporting Center",
    "depends": ["web", "sale_crm", "stock", "purchase", "purchase_stock", "mrp", "maintenance", "mail"],
    "external_dependencies": {
        "python": ["xlsxwriter"],
    },
    "data": [
        "security/dashboard_reporting_security.xml",
        "security/ir.model.access.csv",
        "reports/dashboard_report_templates.xml",
        "reports/dashboard_report_actions.xml",
        "views/executive_dashboard_menu.xml",
        "views/dashboard_alert_views.xml",
        "views/dashboard_reporting_views.xml",
        "data/dashboard_alert_cron.xml",
        "data/dashboard_reporting_cron.xml",
        "data/dashboard_email_template.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "executive_dashboard/static/src/js/components/dashboard_components.js",
            "executive_dashboard/static/src/js/components/dashboard_export_toolbar.js",
            "executive_dashboard/static/src/js/dashboard_base.js",
            "executive_dashboard/static/src/js/executive_overview_dashboard.js",
            "executive_dashboard/static/src/js/sales_dashboard.js",
            "executive_dashboard/static/src/js/crm_dashboard.js",
            "executive_dashboard/static/src/js/inventory_dashboard.js",
            "executive_dashboard/static/src/js/purchase_dashboard.js",
            "executive_dashboard/static/src/js/manufacturing_dashboard.js",
            "executive_dashboard/static/src/js/maintenance_dashboard.js",
            "executive_dashboard/static/src/js/hr_dashboard.js",
            "executive_dashboard/static/src/js/helpdesk_dashboard.js",
            "executive_dashboard/static/src/js/pos_dashboard.js",
            "executive_dashboard/static/src/js/website_dashboard.js",
            "executive_dashboard/static/src/js/alerts_center.js",
            "executive_dashboard/static/src/xml/executive_dashboard.xml",
            "executive_dashboard/static/src/xml/components/dashboard_export_toolbar.xml",
            "executive_dashboard/static/src/scss/executive_dashboard.scss",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
