import re

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError

from ..const import ALLOWED_FIELD_TYPES, PAPERFORMAT_VALUES, PAPERFORMAT_XML_IDS, REPORT_TEMPLATE_XML_ID


HEX_COLOR_RE = re.compile(r"^#[0-9A-Fa-f]{6}$")
COLOR_FIELDS = (
    "primary_color",
    "secondary_color",
    "text_color",
    "table_header_bg_color",
    "table_header_text_color",
    "border_color",
)
STYLE_DEFAULTS = {
    "layout_style": "classic",
    "paper_size": "a4",
    "direction": "ltr",
    "primary_color": "#875A7B",
    "secondary_color": "#F3F4F6",
    "text_color": "#111827",
    "table_header_bg_color": "#875A7B",
    "table_header_text_color": "#FFFFFF",
    "border_color": "#D1D5DB",
    "font_size": 12,
    "title_font_size": 22,
    "show_company_logo": True,
    "show_company_name": True,
    "show_report_title": True,
    "show_footer": True,
    "footer_text": "Generated by Dynamic PDF Report Builder",
    "show_print_date": True,
    "show_page_number": True,
    "table_border_style": "solid",
    "zebra_rows": True,
    "template_preset": False,
}
TEMPLATE_PRESET_VALUES = {
    "classic_business": {
        "layout_style": "classic",
        "direction": "ltr",
        "primary_color": "#875A7B",
        "table_header_bg_color": "#875A7B",
        "table_border_style": "solid",
    },
    "modern_clean": {
        "layout_style": "modern",
        "primary_color": "#2563EB",
        "secondary_color": "#F8FAFC",
        "table_header_bg_color": "#2563EB",
        "table_border_style": "light",
    },
    "arabic_rtl": {
        "direction": "rtl",
        "layout_style": "modern",
        "primary_color": "#0F766E",
        "table_header_bg_color": "#0F766E",
        "show_company_logo": True,
    },
    "minimal_light": {
        "layout_style": "minimal",
        "primary_color": "#111827",
        "table_header_bg_color": "#111827",
        "table_border_style": "none",
        "zebra_rows": False,
    },
    "invoice_style": {
        "layout_style": "classic",
        "show_company_logo": True,
        "show_company_name": True,
        "show_footer": True,
    },
}


class DynamicPdfReport(models.Model):
    _name = "dynamic.pdf.report"
    _description = "Dynamic PDF Report"
    _order = "name, id"

    name = fields.Char(required=True)
    model_id = fields.Many2one(
        "ir.model",
        required=True,
        ondelete="cascade",
        domain=[("transient", "=", False), ("abstract", "=", False)],
    )
    model_name = fields.Char(
        string="Technical Model Name",
        related="model_id.model",
        store=True,
        readonly=True,
    )
    report_title = fields.Char()
    field_line_ids = fields.One2many("dynamic.pdf.report.field", "report_id")
    line_section_ids = fields.One2many("dynamic.pdf.report.line.section", "report_id")
    report_action_id = fields.Many2one(
        "ir.actions.report",
        readonly=True,
        copy=False,
    )
    state = fields.Selection(
        [("draft", "Draft"), ("done", "Done")],
        default="draft",
        required=True,
    )
    layout_style = fields.Selection(
        [("classic", "Classic"), ("modern", "Modern"), ("minimal", "Minimal")],
        default="classic",
        required=True,
    )
    paper_size = fields.Selection(
        [("a4", "A4"), ("a5", "A5")],
        default="a4",
        required=True,
    )
    direction = fields.Selection(
        [("ltr", "Left to Right"), ("rtl", "Right to Left")],
        default="ltr",
        required=True,
    )
    primary_color = fields.Char(default="#875A7B", required=True)
    secondary_color = fields.Char(default="#F3F4F6", required=True)
    text_color = fields.Char(default="#111827", required=True)
    table_header_bg_color = fields.Char(default="#875A7B", required=True)
    table_header_text_color = fields.Char(default="#FFFFFF", required=True)
    border_color = fields.Char(default="#D1D5DB", required=True)
    font_size = fields.Integer(default=12, required=True)
    title_font_size = fields.Integer(default=22, required=True)
    show_company_logo = fields.Boolean(default=True)
    show_company_name = fields.Boolean(default=True)
    show_report_title = fields.Boolean(default=True)
    show_footer = fields.Boolean(default=True)
    footer_text = fields.Char(default="Generated by Dynamic PDF Report Builder")
    show_print_date = fields.Boolean(default=True)
    show_page_number = fields.Boolean(default=True)
    table_border_style = fields.Selection(
        [("none", "None"), ("solid", "Solid"), ("light", "Light")],
        default="solid",
        required=True,
    )
    zebra_rows = fields.Boolean(default=True)
    template_preset = fields.Selection(
        [
            ("classic_business", "Classic Business"),
            ("modern_clean", "Modern Clean"),
            ("arabic_rtl", "Arabic RTL"),
            ("minimal_light", "Minimal Light"),
            ("invoice_style", "Invoice Style"),
        ],
        string="Template Preset",
    )
    last_generated_on = fields.Datetime(readonly=True, copy=False)
    last_generated_by = fields.Many2one("res.users", readonly=True, copy=False)

    @api.onchange("model_id")
    def _onchange_model_id(self):
        if self.field_line_ids:
            self.field_line_ids = False
        if self.line_section_ids:
            self.line_section_ids = False

    @api.constrains("model_id")
    def _check_report_model(self):
        for report in self:
            if report.model_id.transient:
                raise ValidationError(_("You cannot create dynamic PDF reports for transient models."))
            if report.model_id.abstract:
                raise ValidationError(_("You cannot create dynamic PDF reports for abstract models."))

    @api.constrains("model_id", "field_line_ids", "line_section_ids")
    def _check_field_lines_match_model(self):
        for report in self:
            wrong_lines = report.field_line_ids.filtered(
                lambda line: line.field_id and line.field_id.model_id != report.model_id
            )
            if wrong_lines:
                raise ValidationError(_("All selected fields must belong to the selected model."))
            wrong_sections = report.line_section_ids.filtered(
                lambda section: section.one2many_field_id and section.one2many_field_id.model_id != report.model_id
            )
            if wrong_sections:
                raise ValidationError(_("All line sections must use One2many fields from the selected model."))

    @api.constrains(*COLOR_FIELDS)
    def _check_hex_colors(self):
        for report in self:
            report._validate_hex_colors()

    def action_create_report(self):
        for report in self:
            report._validate_report_configuration()
            action = report._get_or_create_report_action()
            report.write({
                "report_action_id": action.id,
                "state": "done",
                "last_generated_on": fields.Datetime.now(),
                "last_generated_by": self.env.user.id,
            })
        return True

    def action_apply_template(self):
        for report in self:
            if not report.template_preset:
                raise UserError(_("Select a template preset before applying a template."))
            report.write(dict(TEMPLATE_PRESET_VALUES[report.template_preset]))
        return True

    def action_reset_styling(self):
        for report in self:
            report.write(dict(STYLE_DEFAULTS))
        return True

    def action_preview_report(self):
        self.ensure_one()
        self._validate_preview_configuration()
        self._validate_report_configuration()
        action = self._get_or_create_report_action()
        self.write({
            "report_action_id": action.id,
            "state": "done",
            "last_generated_on": fields.Datetime.now(),
            "last_generated_by": self.env.user.id,
        })

        preview_record = self._get_preview_record()
        return action.with_context(dynamic_pdf_report_id=self.id).report_action(preview_record, config=False)

    def action_duplicate_design(self):
        self.ensure_one()
        if not self.id:
            raise UserError(_("Save the report before duplicating the design."))

        new_report = self.create(self._prepare_duplicate_design_vals())
        return {
            "type": "ir.actions.act_window",
            "name": _("Copy of %s", self.name),
            "res_model": self._name,
            "res_id": new_report.id,
            "view_mode": "form",
            "target": "current",
        }

    def _validate_preview_configuration(self):
        self.ensure_one()
        if not self.model_id:
            raise UserError(_("Select a model before previewing this report."))
        if not self.field_line_ids.filtered("field_id"):
            raise UserError(_("Add at least one field before previewing this report."))

    def _get_preview_record(self):
        self.ensure_one()
        active_model = self.env.context.get("active_model")
        active_ids = self.env.context.get("active_ids") or []
        active_id = self.env.context.get("active_id")
        if active_id and active_id not in active_ids:
            active_ids = [active_id] + active_ids

        record = self.env[self.model_name]
        if active_model == self.model_name and active_ids:
            record = self.env[self.model_name].browse(active_ids[:1]).exists()
        if not record:
            record = self.env[self.model_name].search([], limit=1)
        if not record:
            raise UserError(_("No records found to preview this report."))
        return record

    def _prepare_duplicate_design_vals(self):
        self.ensure_one()
        vals = {
            "name": _("Copy of %s", self.name),
            "model_id": self.model_id.id,
            "report_title": self.report_title,
            "state": "draft",
            "report_action_id": False,
            "last_generated_on": False,
            "last_generated_by": False,
        }
        for field_name in STYLE_DEFAULTS:
            vals[field_name] = self[field_name]
        vals["field_line_ids"] = [
            (0, 0, {
                "field_id": line.field_id.id,
                "sequence": line.sequence,
                "show_label": line.show_label,
            })
            for line in self.field_line_ids.sorted("sequence")
            if line.field_id
        ]
        vals["line_section_ids"] = [
            (0, 0, {
                "name": section.name,
                "one2many_field_id": section.one2many_field_id.id,
                "sequence": section.sequence,
                "show_section_title": section.show_section_title,
                "line_field_ids": [
                    (0, 0, {
                        "field_id": line.field_id.id,
                        "sequence": line.sequence,
                        "show_label": line.show_label,
                    })
                    for line in section.line_field_ids.sorted("sequence")
                    if line.field_id
                ],
            })
            for section in self.line_section_ids.sorted("sequence")
            if section.one2many_field_id
        ]
        return vals

    def _validate_report_configuration(self):
        self.ensure_one()
        if not self.model_id:
            raise UserError(_("Select a model before creating the report."))
        if self.model_id.transient:
            raise UserError(_("Transient models cannot be used for dynamic PDF reports."))
        if self.model_id.abstract:
            raise UserError(_("Abstract models cannot be used for dynamic PDF reports."))
        if not self.model_name or self.model_name not in self.env:
            raise UserError(_("The selected model is not available in the registry."))
        self._validate_hex_colors()

        field_lines = self.field_line_ids.filtered("field_id")
        if not field_lines:
            raise UserError(_("Add at least one field before creating the report."))

        field_ids = field_lines.mapped("field_id").ids
        if len(field_ids) != len(set(field_ids)):
            raise UserError(_("A field can only be selected once in the same report."))

        invalid_lines = field_lines.filtered(lambda line: line.field_type not in ALLOWED_FIELD_TYPES)
        if invalid_lines:
            allowed_types = ", ".join(ALLOWED_FIELD_TYPES)
            raise UserError(_("Phase 1 supports only these field types: %s", allowed_types))

        wrong_lines = field_lines.filtered(lambda line: line.field_id.model_id != self.model_id)
        if wrong_lines:
            raise UserError(_("All selected fields must belong to the selected model."))

        self._validate_line_sections()

    def _validate_line_sections(self):
        self.ensure_one()
        sections = self.line_section_ids
        if not sections:
            return

        section_field_ids = []
        for section in sections.sorted("sequence"):
            if not section.one2many_field_id:
                raise UserError(_("Line section '%s' must have a One2many field.", section.name or _("New")))
            if section.one2many_field_id.ttype != "one2many":
                raise UserError(
                    _("Line section '%s' must use a One2many field.", section.name or section.one2many_field_id.name)
                )
            if section.one2many_field_id.model_id != self.model_id:
                raise UserError(
                    _("Line section '%s' must use a One2many field from the selected report model.", section.name)
                )
            if not section.related_model_name or section.related_model_name not in self.env:
                raise UserError(
                    _("Line section '%s' has an invalid related model. Check the One2many field relation.", section.name)
                )

            section_field_ids.append(section.one2many_field_id.id)
            line_fields = section.line_field_ids.filtered("field_id")
            if not line_fields:
                raise UserError(_("Line section '%s' must contain at least one line field.", section.name))

            line_field_ids = line_fields.mapped("field_id").ids
            if len(line_field_ids) != len(set(line_field_ids)):
                raise UserError(_("Line section '%s' contains duplicate line fields.", section.name))

            invalid_fields = line_fields.filtered(lambda line: line.field_type not in ALLOWED_FIELD_TYPES)
            if invalid_fields:
                allowed_types = ", ".join(ALLOWED_FIELD_TYPES)
                raise UserError(_("Line sections support only these field types: %s", allowed_types))

            wrong_fields = line_fields.filtered(lambda line: line.field_id.model_id != section.related_model_id)
            if wrong_fields:
                raise UserError(
                    _("All line fields in section '%s' must belong to the One2many related model.", section.name)
                )

        if len(section_field_ids) != len(set(section_field_ids)):
            raise UserError(_("A One2many field can only be used once in the same dynamic report."))

    def _get_or_create_report_action(self):
        self.ensure_one()
        ReportAction = self.env["ir.actions.report"].sudo()
        action = self.report_action_id.sudo().exists()
        if not action:
            action = ReportAction.search([("dynamic_pdf_report_id", "=", self.id)], limit=1)

        action_vals = self._prepare_report_action_vals()
        if action:
            action.write(action_vals)
        else:
            action = ReportAction.create(action_vals)
        return action

    def _prepare_report_action_vals(self):
        self.ensure_one()
        return {
            "name": self.name,
            "model": self.model_name,
            "report_type": "qweb-pdf",
            "report_name": REPORT_TEMPLATE_XML_ID,
            "report_file": REPORT_TEMPLATE_XML_ID,
            "binding_model_id": self.model_id.id,
            "binding_type": "report",
            "binding_view_types": "list,form",
            "context": "{'dynamic_pdf_report_id': %d}" % self.id,
            "paperformat_id": self._get_paperformat().id,
            "dynamic_pdf_report_id": self.id,
        }

    def _validate_hex_colors(self):
        self.ensure_one()
        for field_name in COLOR_FIELDS:
            value = (self[field_name] or "").strip()
            if not HEX_COLOR_RE.match(value):
                field_label = self._fields[field_name].string
                raise UserError(_("%(field)s must be a valid hex color like #FFFFFF.", field=field_label))

    def _get_paperformat(self):
        self.ensure_one()
        paper_size = self.paper_size or "a4"
        xml_id = PAPERFORMAT_XML_IDS[paper_size]
        paperformat = self.env.ref(xml_id, raise_if_not_found=False)
        if paperformat:
            return paperformat

        values = dict(PAPERFORMAT_VALUES[paper_size])
        paperformat = self.env["report.paperformat"].sudo().search([("name", "=", values["name"])], limit=1)
        if paperformat:
            paperformat.write(values)
        else:
            paperformat = self.env["report.paperformat"].sudo().create(values)
        return paperformat


class DynamicPdfReportField(models.Model):
    _name = "dynamic.pdf.report.field"
    _description = "Dynamic PDF Report Field"
    _order = "sequence, id"

    _unique_report_field = models.Constraint(
        "unique(report_id, field_id)",
        "A field can only be selected once in the same report.",
    )

    report_id = fields.Many2one(
        "dynamic.pdf.report",
        required=True,
        ondelete="cascade",
    )
    field_id = fields.Many2one("ir.model.fields", required=True, ondelete="cascade")
    field_name = fields.Char(related="field_id.name", store=True, readonly=True)
    field_description = fields.Char(related="field_id.field_description", store=True, readonly=True)
    field_type = fields.Selection(related="field_id.ttype", store=True, readonly=True)
    sequence = fields.Integer(default=10)
    show_label = fields.Boolean(default=True)

    @api.constrains("field_id", "report_id")
    def _check_field_id(self):
        for line in self:
            if line.field_id.model_id != line.report_id.model_id:
                raise ValidationError(_("The selected field must belong to the report model."))
            if line.field_type not in ALLOWED_FIELD_TYPES:
                allowed_types = ", ".join(ALLOWED_FIELD_TYPES)
                raise ValidationError(_("Phase 1 supports only these field types: %s", allowed_types))


class DynamicPdfReportLineSection(models.Model):
    _name = "dynamic.pdf.report.line.section"
    _description = "Dynamic PDF Report Line Section"
    _order = "sequence, id"

    _unique_report_one2many_field = models.Constraint(
        "unique(report_id, one2many_field_id)",
        "A One2many field can only be used once in the same dynamic report.",
    )

    report_id = fields.Many2one(
        "dynamic.pdf.report",
        required=True,
        ondelete="cascade",
    )
    name = fields.Char(required=True)
    one2many_field_id = fields.Many2one(
        "ir.model.fields",
        required=True,
        ondelete="cascade",
        domain=[("ttype", "=", "one2many")],
    )
    one2many_field_name = fields.Char(
        string="One2many Technical Name",
        related="one2many_field_id.name",
        store=True,
        readonly=True,
    )
    related_model_id = fields.Many2one(
        "ir.model",
        compute="_compute_related_model",
        store=True,
        readonly=True,
    )
    related_model_name = fields.Char(
        compute="_compute_related_model",
        store=True,
        readonly=True,
    )
    line_field_ids = fields.One2many("dynamic.pdf.report.line.field", "section_id")
    sequence = fields.Integer(default=10)
    show_section_title = fields.Boolean(default=True)

    @api.depends("one2many_field_id.relation")
    def _compute_related_model(self):
        IrModel = self.env["ir.model"]
        for section in self:
            related_model = False
            if section.one2many_field_id.relation:
                related_model = IrModel.search([("model", "=", section.one2many_field_id.relation)], limit=1)
            section.related_model_id = related_model
            section.related_model_name = related_model.model if related_model else False

    @api.onchange("one2many_field_id")
    def _onchange_one2many_field_id(self):
        if self.one2many_field_id:
            if not self.name:
                self.name = self.one2many_field_id.field_description or self.one2many_field_id.name
            if self.line_field_ids:
                self.line_field_ids = False

    @api.constrains("one2many_field_id", "report_id", "related_model_id")
    def _check_one2many_field_id(self):
        for section in self:
            if not section.report_id or not section.one2many_field_id:
                continue
            if section.one2many_field_id.ttype != "one2many":
                raise ValidationError(_("Line sections must use One2many fields."))
            if section.one2many_field_id.model_id != section.report_id.model_id:
                raise ValidationError(_("The One2many field must belong to the selected report model."))
            if not section.related_model_id or section.related_model_name not in self.env:
                raise ValidationError(_("The selected One2many field has an invalid relation model."))
            wrong_fields = section.line_field_ids.filtered(
                lambda line: line.field_id and line.field_id.model_id != section.related_model_id
            )
            if wrong_fields:
                raise ValidationError(_("All line fields must belong to the One2many related model."))


class DynamicPdfReportLineField(models.Model):
    _name = "dynamic.pdf.report.line.field"
    _description = "Dynamic PDF Report Line Field"
    _order = "sequence, id"

    _unique_section_field = models.Constraint(
        "unique(section_id, field_id)",
        "A line field can only be selected once in the same line section.",
    )

    section_id = fields.Many2one(
        "dynamic.pdf.report.line.section",
        required=True,
        ondelete="cascade",
    )
    field_id = fields.Many2one(
        "ir.model.fields",
        required=True,
        ondelete="cascade",
        domain=[("ttype", "in", ALLOWED_FIELD_TYPES)],
    )
    field_name = fields.Char(related="field_id.name", store=True, readonly=True)
    field_description = fields.Char(related="field_id.field_description", store=True, readonly=True)
    field_type = fields.Selection(related="field_id.ttype", store=True, readonly=True)
    sequence = fields.Integer(default=10)
    show_label = fields.Boolean(default=True)

    @api.constrains("field_id", "section_id")
    def _check_field_id(self):
        for line in self:
            if not line.field_id or not line.section_id:
                continue
            if line.field_type not in ALLOWED_FIELD_TYPES:
                allowed_types = ", ".join(ALLOWED_FIELD_TYPES)
                raise ValidationError(_("Line sections support only these field types: %s", allowed_types))
            if line.section_id.related_model_id and line.field_id.model_id != line.section_id.related_model_id:
                raise ValidationError(_("The selected line field must belong to the One2many related model."))
