from odoo import api, fields, models


class ExecutiveDashboardReportLog(models.Model):
    _name = "executive.dashboard.report.log"
    _description = "Dashboard Report Log"
    _order = "generated_datetime DESC"

    name = fields.Char(string="Log Name", required=True)
    dashboard_key = fields.Char(string="Dashboard Key")
    dashboard_name = fields.Char(string="Dashboard Name")
    report_type = fields.Selection(
        [("export", "Export"), ("snapshot", "Snapshot"), ("share", "Share"), ("scheduled", "Scheduled")],
        string="Report Type", required=True,
    )
    format = fields.Selection(
        [("pdf", "PDF"), ("excel", "Excel"), ("both", "PDF & Excel")],
        string="Format",
    )
    generated_by = fields.Many2one("res.users", string="Generated By", default=lambda self: self.env.user)
    generated_datetime = fields.Datetime(string="Generated Date/Time", default=fields.Datetime.now)
    company_id = fields.Many2one("res.company", default=lambda self: self.env.company)
    recipients = fields.Char(string="Recipients")
    schedule_id = fields.Many2one("executive.dashboard.report.schedule", string="Schedule")
    status = fields.Selection([("success", "Success"), ("failed", "Failed")], string="Status", default="success")
    error_message = fields.Text(string="Error Message")
    attachment_ids = fields.Many2many("ir.attachment", string="Attachments")
    filters_json = fields.Json(string="Filters", default=dict)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get("name"):
                dashboard_name = vals.get("dashboard_name", "Report")
                report_type = vals.get("report_type", "export")
                timestamp = fields.Datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                vals["name"] = f"{dashboard_name} - {report_type} - {timestamp}"
            vals.setdefault("generated_by", self.env.user.id)
            vals.setdefault("company_id", self.env.company.id)
        return super().create(vals_list)
