from odoo import _, api, fields, models


class ResConfigSettings(models.TransientModel):
    _inherit = "res.config.settings"

    executive_dashboard_default_recipient_ids = fields.Many2many(
        "res.partner",
        "executive_dashboard_settings_partner_rel",
        "settings_id",
        "partner_id",
        string="Default Recipients",
        domain=[("email", "!=", False)],
    )
    executive_dashboard_default_frequency = fields.Selection(
        [("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
        string="Default Frequency",
        default="daily",
    )
    executive_dashboard_default_export_max_rows = fields.Integer(
        string="Default Export Max Rows",
        default=500,
        help="Maximum rows per exported table. Values are clamped between 1 and 5000.",
    )
    executive_dashboard_include_charts = fields.Boolean(string="Include Charts by Default")
    executive_dashboard_include_tables = fields.Boolean(string="Include Tables by Default")
    executive_dashboard_include_kpis = fields.Boolean(string="Include KPIs by Default")
    executive_dashboard_pdf_footer_text = fields.Char(
        string="PDF Footer Text",
        default=lambda self: _("Generated by Executive Dashboard"),
    )
    executive_dashboard_use_company_logo = fields.Boolean(string="Use Company Logo in PDF")

    @api.model
    def get_values(self):
        res = super().get_values()
        settings = self.env["executive.dashboard.export"].get_report_settings()
        res.update(
            executive_dashboard_default_recipient_ids=[(6, 0, settings["default_recipient_ids"])],
            executive_dashboard_default_frequency=settings["default_frequency"],
            executive_dashboard_default_export_max_rows=settings["default_export_max_rows"],
            executive_dashboard_include_charts=settings["include_charts"],
            executive_dashboard_include_tables=settings["include_tables"],
            executive_dashboard_include_kpis=settings["include_kpis"],
            executive_dashboard_pdf_footer_text=settings["pdf_footer_text"],
            executive_dashboard_use_company_logo=settings["use_company_logo"],
        )
        return res

    def set_values(self):
        super().set_values()
        max_rows = min(5000, max(1, self.executive_dashboard_default_export_max_rows or 500))
        # sudo: ir.config_parameter stores technical reporting defaults, not business data.
        params = self.env["ir.config_parameter"].sudo()
        params.set_param(
            "executive_dashboard.reporting.default_recipient_ids",
            ",".join(str(partner_id) for partner_id in self.executive_dashboard_default_recipient_ids.ids),
        )
        params.set_param(
            "executive_dashboard.reporting.default_frequency",
            self.executive_dashboard_default_frequency or "daily",
        )
        params.set_param("executive_dashboard.reporting.default_export_max_rows", max_rows)
        params.set_param("executive_dashboard.reporting.include_charts", self.executive_dashboard_include_charts)
        params.set_param("executive_dashboard.reporting.include_tables", self.executive_dashboard_include_tables)
        params.set_param("executive_dashboard.reporting.include_kpis", self.executive_dashboard_include_kpis)
        params.set_param(
            "executive_dashboard.reporting.pdf_footer_text",
            self.executive_dashboard_pdf_footer_text or "",
        )
        params.set_param(
            "executive_dashboard.reporting.use_company_logo",
            self.executive_dashboard_use_company_logo,
        )
